services:
  proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /app/certs:/etc/nginx/certs:ro
      # - /etc/nginx/vhost.d
      # - /usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - HTTPS_METHOD=noredirect
    networks:
      - web

  proxy-ssl:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /app/certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=itkalmia@kalmia.si
    networks:
      - web

networks:
  web:
    name: web
